// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBn86vXReGjfTmPpuSsWqOsOoEKcqr3oY',
    appId: '1:696271793828:web:4e6083e56e507ffaa40031',
    messagingSenderId: '696271793828',
    projectId: 'loginauth-a2ad4',
    authDomain: 'loginauth-a2ad4.firebaseapp.com',
    storageBucket: 'loginauth-a2ad4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChn-fMOksTT1UPq7FnIj_TLg666FWMEbc',
    appId: '1:696271793828:android:ae6b07185fa475faa40031',
    messagingSenderId: '696271793828',
    projectId: 'loginauth-a2ad4',
    storageBucket: 'loginauth-a2ad4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25KtjOA8p0Xo8cxejOC-BvF0JgaCy3rY',
    appId: '1:696271793828:ios:6742efd64e904cf0a40031',
    messagingSenderId: '696271793828',
    projectId: 'loginauth-a2ad4',
    storageBucket: 'loginauth-a2ad4.appspot.com',
    iosBundleId: 'com.sagredina.apexstatusmobile.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25KtjOA8p0Xo8cxejOC-BvF0JgaCy3rY',
    appId: '1:696271793828:ios:3e14709dc4604ef7a40031',
    messagingSenderId: '696271793828',
    projectId: 'loginauth-a2ad4',
    storageBucket: 'loginauth-a2ad4.appspot.com',
    iosBundleId: 'com.sagredina.apexstatusmobile.loginUi.RunnerTests',
  );
}
